Countries = [
    "Saint Kitts and Nevis",
    "Trinidad and Tobago",
    "Tanzania",
    "Congo",
    "Tuvalu",
    "Serbia",
    "Nauru",
    "Thailand",
    "Lesotho",
    "Peru",
    "Poland",
    "Kosovo",
    "Liberia",
    "Portugal",
    "Norway",
    "Denmark",
    "Dominica",
    "Saint Vincent and the Grenadines",
    "El Salvador",
    "France",
    "Albania",
    "Honduras",
    "Lithuania",
    "Monaco",
    "Malaysia",
    "Finland",
    "Guatemala",
    "Hong Kong",
    "Bulgaria",
    "Australia",
    "Paraguay",
    "Chile",
    "Czech Republic",
    "India",
    "Iraq",
    "Belize",
    "Croatia",
    "Panama",
    "Jamaica",
    "Japan",
    "Philippines",
    "Iceland",
    "Sierra Leone",
    "Zambia",
    "Bolivia",
    "Gambia",
    "North Macedonia",
    "Eswatini",
    "Belgium",
    "Italy",
    "Suriname",
    "Switzerland",
    "Pakistan",
    "Guyana",
    "Luxembourg",
    "Brazil",
    "Malawi",
    "Mexico",
    "Sweden",
    "Kiribati",
    "Austria",
    "Fiji",
    "Ireland",
    "New Zealand",
    "Micronesia",
    "Uruguay",
    "Zimbabwe",
    "Bahamas",
    "Myanmar",
    "Seychelles",
    "Nicaragua",
    "Grenada",
    "Argentina",
    "Nigeria",
    "Cuba",
    "Papua New Guinea",
    "Tonga",
    "Marshall Islands",
    "Spain",
    "Hungary",
    "Germany",
    "Ghana",
    "Mauritius",
    "Unite",
    "Colombia",
    "South Africa",
    "Greece",
    "Sri Lanka",
    "South Korea",
    "Cyprus",
    "Montenegro",
    "Liechtenstein",
    "Netherlands",
    "Slovenia",
    "Ecuador",
    "San Marino",
    "Turkey",
    "Antigua and Barbuda",
    "Egypt",
    "Jordan",
    "Kenya",
    "Israel",
    "Barbados",
    "Haiti",
    "Costa Rica",
    "Bosnia and Herzegovina"
]
